### ISSUE TITLE
No prebuild binary as github release

### ISSUE THREAD

**Issue by joernroeder** [hypriot/docker-machine-hypriot#4]
Hey, i would love to fire up containers on my pi with docker-machine-hypriot but couldn't find the release as described in the readme. can you upload/tag the latest version?
thanks in advance!

**Comment by joernroeder** [comment]
just found the binaries here. http://blog.hypriot.com/downloads/

**Comment by StefanScherer** [comment]
@joernroeder right. This repo is a work in progress for a docker-machine driver plugin. But we soon found out that we more need a provisioner plugin instead. So please use the docker-machine-hypriot binary of version 0.4.1 from our download page.

**Comment by joernroeder** [comment]
that’s what i did. Works like a charm! thanks
